### ISSUE TITLE
how to have more variables in ULP code

### ISSUE THREAD

**Issue by vencax** [micropython/micropython-esp32-ulp#103]
Hi, i have this code:
```
...
counter:	.long 0

entry:
...            
```
I read the counter from main core like this:
```
ULP_MEM_BASE = const(0x50000000)
ULP_DATA_MASK = const(0xffff)
mem32[ULP_MEM_BASE] & ULP_DATA_MASK
```
but when I add another variable, it stops working (meaning I read zeros from main core all the time):
```
...
counter:	.long 0
threshold:      .long 0

entry:
...       
```

what I am doing wrong?

**Comment by vencax** [comment]
Ha, silly bug. Its necessary to set proper __entry_addr__ when starting the ULP program. When there is 2 variables, then __entry_addr__ must be 8. Following formula can be used:
```
entry_addr = 4 * <nuber of variables>
```
because variables are aligned in memory to 4 bytes.

NOTE:
I was struggling with sections in asm as well. I tried put variables into .data or into .bss sections. Result:
__there is no need to use sections. You can omit sections completely (the code is put into .text section by default).__

**Comment by wnienhaus** [comment]
Great. That is what I would have assumed - about the entry point offset.
However, are you saying that using the .data or .bss sections has no impact?
Theoretically anything in .data should go after the code (.text) and anything from .bss goes after data (without actually being put into the image).
