### ISSUE TITLE
binary file should be open with 'rb' instead of 'r' in advanced exemple

### ISSUE THREAD

**Issue by pidou46** [micropython/micropython-esp32-ulp#99]
With mp 1.24 , in advanced usage exemple: <with open('test.ulp', 'r') as f:> rise a unicode exception

It should be changed to:
<with open('test.ulp', 'rb') as f:>

**Comment by ThomasWaldmann** [comment]
guess this refers to item 3 there: https://github.com/micropython/micropython-esp32-ulp/blob/master/docs/index.rst#advanced-usage

sure, reading binary files should always use "rb" mode.

can you submit a PR?

**Comment by pidou46** [comment]
Yes, it's.
  
I will try to submit a PR, m'y knowlage with git is very thinght but the modification is trivial so I shoud be able to do it.
  
The code worked with earlier mp version, so I guess I should try to see if this PR would work with previous mp versions (1.12 ?) priori to submit it?
  

  

  
  
  
  
>

**Comment by ThomasWaldmann** [comment]
I don't think you need to check with old micropython versions, just with the current one.

**Comment by wnienhaus** [comment]
Fixed by #100
